<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.addons.bundles</groupId>
    <artifactId>org.openhab.addons.reactor.bundles</artifactId>
    <version>5.1.0-SNAPSHOT</version>
  </parent>

  <artifactId>org.openhab.binding.octopusapi</artifactId>
  <version>5.0.0</version>

  <name>openHAB Add-ons :: Bundles :: Octopus API Binding</name>
  <dependencies>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.11.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>biz.aQute.bnd</groupId>
        <artifactId>bnd-maven-plugin</artifactId>
        <configuration>
          <bnd><![CDATA[
            -exportcontents: !*
            -includeresource: @gson-*.jar!/com/google/gson/**
            Import-Package: \
              !com.google.gson.*, \
              org.openhab.core.*;version="[5.0.0,6.0.0)", \
              *
          ]]></bnd>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
